### ISSUE TITLE
Some questions about the proof of Theorem 3.2

### ISSUE THREAD

**Issue by wzfhaha** [yshenaw/GF_CF#1]
Dear Authors,
    I have some questions about the proof of theorem 3.2 in Section 8.2. Concretely, I am very confusing about the derivation of the limitation of $S$ when $d$ tends to infinity. I am also confusing about the statement 
> For a pair of matrices  X, Y, if the rows of X \in R^{* \times d}, Y \in R^{* \times d} follow independently identical distribution, due to the linearity of dot product, we have lim_{d -> \inf} X Y^T = \mathbb{E}[x_1 y_1^T].

Why do the above equations hold? Can you explain more about that? Thanks very much!

**Comment by yshenaw** [comment]
Considering i.i.d. variables a_1, \cdots, a_d, b_1, \cdots, b_d, \lim_{d \rightarrow \infty} \frac{1}{d} \sum_{i=1}^d a_i b_i = \mathbb{E} a_1 b_1. 
ps: You can leave your WeChat number here and thus we can have better communication.

**Comment by wzfhaha** [comment]
OK, my wechat ID is 17888821672 .

**Comment by lxd99** [comment]
@yshenaw, thanks for the great work! I also have the same question about the statement in proof of Theorem 3.2.
> For a pair of matrices X, Y, if the rows of $X \in R^{* \times d}, Y \in R^{* \times d}$ follow independently identical distribution, due to the linearity of dot product, we have $lim_{d -> \inf} X Y^T = \mathbb{E}[x_1 y_1^T]$ , where $x_1$ (resp. $y_1$) denotes the first column of X (resp. Y)

Consider the element in the first row and column of $XY^T$, which should be 
``` math
\sum_{k=1}^d X_{1,k} * Y_{1,k},
```
where $X_{1,k}$ and $Y_{1,k}$ mean the element in the first row and kth column of X and Y respectively. 

If the $lim_{d -> \inf} X Y^T = \mathbb{E}[x_1 y_1^T]$ holds, it is to say 
``` math
lim_{d -> \inf} \sum_{k=1}^d X_{1,k} * Y_{1,k} = \mathbb{E}[X_{1,1}*Y_{1,1}] ,
```
I am afraid that the left side needs to be multiplied a $1/{d}$ so the above equation can hold.

Do I miss some key points? Looking forward for you reply！
