### ISSUE TITLE
Questions about the proofs

### ISSUE THREAD

**Issue by wujcan** [yshenaw/GF_CF#3]
Dear authors,

I have some questions about the proof of Theorem 3.1 and 3.2. 

Specifically,  in Proof of Theorem 3.1, I don't understand why this inequality holds
![2021-12-16_143742](https://user-images.githubusercontent.com/45536153/146320700-d0221409-691b-4311-9f62-d7abb4c02583.png)

Also, from reference [42] (High-Dimensional Data Analysis with Low-Dimensional Models: Principles, Computation, and Applications), the mutual coherence of a matrix is the largest normalized inner product between two distinct columns, instead of rows (embedding is a row vector of a matrix). In Lemma 8.1, A is an n x m matrix, while in Theorem 3.5 of [42], A is an m x n matrix. 

So I am really confused about the conclusion of Theorem 3.1 in your paper. Do I have some misunderstandings?
![2021-12-16_152952](https://user-images.githubusercontent.com/45536153/146327100-b1a9d473-4965-4d78-8463-18782414ae62.png)

![2021-12-16_152559](https://user-images.githubusercontent.com/45536153/146326705-f41662f9-57a9-447d-ada9-b37491bd7661.png)

In Proof of Theorem 3.2, the conclusion is
![2021-12-16_154815](https://user-images.githubusercontent.com/45536153/146329595-8afab425-4ac9-4c7f-9ba3-1335f46ba684.png)

But taking a two-layer LightGCN as an example, 
![2021-12-16_155119](https://user-images.githubusercontent.com/45536153/146330024-1507f421-5aec-48c1-bd45-bae998598759.png)

I am afraid the multiply of two underlined terms can not be represented by \beta_k R (R^T R)^k for any k.

I am looking forward to your reply!

**Comment by yshenaw** [comment]
1. In [42], the columns are i.i.d. taken from unif(S^{m-1}) while in this paper the rows are taken from unif(S^{m-1}). So we can apply the theorem.
2. Notice that if U_0 and V_0 are independent, we have \mathbb{E}[U_0V_0] = 0 and this term is 0.

Thanks a lot for your interest in our work! You can also add my WeChat (for in-time communication) if you have further questions. I can send you my WeChat number through e-mail.

**Comment by wujcan** [comment]
Thanks a lot for your reply! I can get your point. I still have a minor question,

By replacing n to (|U|+|I|) and m=d>XXXXX in lemma 8.1, we get \epsilon<\sqrt(CN_{min}/N_{max}^3), instead of \epsilon<\sqrt (N_{min}/2N_{max}^3).

**Comment by yshenaw** [comment]
A nice catch! I put another constant in dimension d to eliminate the constant C in \epsilon<\sqrt(CN_{min}/N_{max}^3).
But I think I abuse the notations...  C in (10) and C lemma 8.1 should be different constants. Thank you a lot~

**Comment by wujcan** [comment]
Thanks again for your reply! This really helps!
